import { StyleSheet } from '@react-pdf/renderer';

export const LEASE_PDF_PRIMARY = '#B100D6';
export const LEASE_PDF_SECONDARY = '#6D28D9';
export const LEASE_PDF_LIGHT = '#F8FAFC';
export const LEASE_PDF_BORDER = '#E2E8F0';

export const leasePdfStyles = StyleSheet.create({
  coverPage: { backgroundColor: '#fff', padding: 0, position: 'relative' },
  coverHero: { position: 'absolute', top: 0, left: 0, right: 0, height: 268 },
  coverOverlay1: {
    position: 'absolute',
    top: 208,
    left: 0,
    right: 0,
    height: 128,
    backgroundColor: LEASE_PDF_PRIMARY,
  },
  coverOverlay2: {
    position: 'absolute',
    top: 248,
    left: 0,
    right: 0,
    height: 128,
    backgroundColor: LEASE_PDF_SECONDARY,
    opacity: 0.9,
  },
  coverAccentBar: {
    position: 'absolute',
    top: 268,
    left: 0,
    width: 6,
    height: 420,
    backgroundColor: LEASE_PDF_PRIMARY,
  },
  coverBody: { paddingTop: 288, paddingLeft: 48, paddingRight: 36, paddingBottom: 32 },
  coverMainRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  coverLogoColumn: { width: 172, alignItems: 'center', paddingTop: 4 },
  coverRightColumn: { flex: 1, paddingLeft: 14, minWidth: 0 },
  logoCard: {
    width: 156,
    height: 156,
    borderRadius: 78,
    backgroundColor: '#1e293b',
    borderWidth: '0pt' as const,
    borderColor: 'transparent',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  /** Fallback Smartimmo : pastille violette + monogramme */
  logoCardBrand: {
    width: 156,
    height: 156,
    borderRadius: 78,
    backgroundColor: '#5B21B6',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoImage: { width: 156, height: 156, objectFit: 'cover' },
  brandMarkInner: { alignItems: 'center', justifyContent: 'center', width: '100%', paddingVertical: 6 },
  brandMonogramCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: LEASE_PDF_PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  brandMonogramLetter: { fontSize: 34, fontWeight: 'bold', color: '#ffffff' },
  brandWordmark: { fontSize: 11, fontWeight: 'bold', color: '#ffffff', letterSpacing: 2.4 },
  brandTagline: { fontSize: 6.5, color: 'rgba(255,255,255,0.55)', marginTop: 3, letterSpacing: 0.8 },
  agencyCard: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: '#fafafa',
    borderWidth: 1,
    borderColor: LEASE_PDF_BORDER,
    borderLeftWidth: 4,
    borderLeftColor: LEASE_PDF_PRIMARY,
    marginBottom: 12,
  },
  agencyEyebrow: {
    fontSize: 7,
    fontWeight: 'bold',
    color: LEASE_PDF_SECONDARY,
    letterSpacing: 1.4,
    marginBottom: 5,
  },
  agencyTitle: { fontSize: 15, fontWeight: 'bold', marginBottom: 5, color: '#0f172a' },
  agencyLine: { fontSize: 9.5, color: '#475569', marginBottom: 2 },
  coverTitleBlock: { marginTop: 2 },
  coverTitleRule: {
    width: 36,
    height: 3,
    backgroundColor: LEASE_PDF_PRIMARY,
    marginBottom: 8,
    borderRadius: 1,
    borderWidth: '0pt' as const,
    borderColor: 'transparent',
  },
  coverTitle: { fontSize: 22, fontWeight: 'bold', color: '#111827', marginBottom: 3, lineHeight: 1.22 },
  coverTitleHint: {
    fontSize: 9,
    color: LEASE_PDF_SECONDARY,
    fontWeight: 'bold',
    marginBottom: 5,
    letterSpacing: 1.8,
  },
  coverSubtitle: { fontSize: 11, color: '#64748b', marginBottom: 4 },
  coverMeta: { fontSize: 8, color: '#94a3b8', marginTop: 12, lineHeight: 1.5, maxWidth: '100%' },

  page: {
    backgroundColor: '#fff',
    paddingTop: 48,
    paddingHorizontal: 34,
    paddingBottom: 42,
    fontSize: 10,
    color: '#111827',
  },
  pageHeader: {
    position: 'absolute',
    top: 14,
    left: 34,
    right: 34,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: LEASE_PDF_BORDER,
    paddingBottom: 8,
  },
  pageHeaderBrand: { fontSize: 9, fontWeight: 'bold', color: LEASE_PDF_SECONDARY },
  pageHeaderRef: { fontSize: 8, color: '#64748B' },

  sectionHeader: {
    backgroundColor: LEASE_PDF_PRIMARY,
    borderRadius: 6,
    borderWidth: '0pt' as const,
    borderColor: 'transparent',
    paddingVertical: 6,
    paddingHorizontal: 11,
    marginTop: 10,
    marginBottom: 8,
  },
  /** Première section en tête de page corps */
  sectionHeaderPageLead: { marginTop: 6 },
  /** Première clause du bloc « clauses finales + signature » */
  sectionHeaderClauseLead: { marginTop: 5 },
  sectionHeaderText: {
    color: '#fff',
    fontSize: 10.5,
    fontWeight: 'bold',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  card: {
    borderWidth: 1,
    borderColor: LEASE_PDF_BORDER,
    borderRadius: 10,
    backgroundColor: LEASE_PDF_LIGHT,
    padding: 10,
    marginBottom: 8,
  },
  subTitle: { fontSize: 11, fontWeight: 'bold', marginBottom: 5, color: '#0F172A' },
  paragraph: { fontSize: 10, lineHeight: 1.48, color: '#1F2937', marginBottom: 5, textAlign: 'justify' },
  bullet: { fontSize: 10, lineHeight: 1.42, marginBottom: 3, paddingLeft: 4, textAlign: 'justify' },
  legalMention: { fontSize: 9.5, lineHeight: 1.45, color: '#334155', fontStyle: 'italic', marginTop: 4 },

  table: { borderWidth: 1, borderColor: LEASE_PDF_BORDER, borderRadius: 8, overflow: 'hidden', marginBottom: 10 },
  tableHead: { flexDirection: 'row', backgroundColor: '#F1F5F9', borderBottomWidth: 1, borderBottomColor: LEASE_PDF_BORDER },
  tableHeadCell: { flex: 1, fontSize: 10, fontWeight: 'bold', paddingVertical: 7, paddingHorizontal: 8 },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#EEF2F7' },
  tableRowLast: { borderBottomWidth: 0, borderBottomColor: 'transparent' },
  tableCell: { flex: 1, fontSize: 10, paddingVertical: 6, paddingHorizontal: 8 },
  tableCellRight: {
    flex: 1,
    fontSize: 10,
    paddingVertical: 6,
    paddingHorizontal: 8,
    textAlign: 'right',
    fontWeight: 'bold',
  },

  clauseBox: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    padding: 10,
    marginBottom: 8,
  },
  clauseBoxTitle: { fontSize: 10.5, fontWeight: 'bold', marginBottom: 6, color: '#0F172A' },

  signatureWrap: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: LEASE_PDF_BORDER,
  },
  signTitle: { fontSize: 15, fontWeight: 'bold', marginBottom: 8, color: '#111827' },
  signRow: { flexDirection: 'row' },
  signCol: {
    flex: 1,
    borderWidth: 1,
    borderColor: LEASE_PDF_BORDER,
    borderRadius: 10,
    padding: 10,
    minHeight: 128,
  },
  signColSpacer: { width: 6, borderWidth: '0pt' as const, borderColor: 'transparent' },
  signColTitle: { fontSize: 11, fontWeight: 'bold', marginBottom: 8, color: LEASE_PDF_PRIMARY },
  signName: { fontSize: 10, marginBottom: 6 },
  signLine: { borderBottomWidth: 1, borderBottomColor: '#334155', marginTop: 22, marginBottom: 4 },
  signatureImg: { width: 120, height: 44, objectFit: 'contain', marginTop: 6 },
  signHint: { fontSize: 9, color: '#64748B' },

  footer: {
    position: 'absolute',
    left: 34,
    right: 34,
    bottom: 16,
    borderTopWidth: 1,
    borderTopColor: LEASE_PDF_BORDER,
    paddingTop: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerText: { fontSize: 8.5, color: '#64748B' },
  pageNumber: { fontSize: 8.5, color: '#64748B' },
});
