import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Seeds pour les types de documents unifiés
 * Couvre les contextes: global, property, lease, transaction
 */

export const documentTypesSeed = [
  // GLOBAL - Documents généraux
  {
    code: 'CONTRAT_ASSURANCE',
    label: 'Contrat d\'assurance',
    description: 'Contrat d\'assurance habitation, PNO, GLI',
    scope: 'global',
    isSystem: true,
    isRequired: false,
    isActive: true,
    isSensitive: false,
    order: 10,
    icon: 'Shield',
    autoAssignThreshold: 0.85,
    validExtensions: JSON.stringify(['.pdf', '.jpg', '.jpeg', '.png']),
    validMimeTypes: JSON.stringify(['application/pdf', 'image/jpeg', 'image/png']),
    versioningEnabled: true,
  },
  {
    code: 'FACTURE',
    label: 'Facture',
    description: 'Facture de travaux, d\'entretien, etc.',
    scope: 'global',
    isSystem: false,
    isRequired: false,
    isActive: true,
    isSensitive: false,
    order: 20,
    icon: 'Receipt',
    validExtensions: JSON.stringify(['.pdf', '.jpg', '.jpeg', '.png']),
    validMimeTypes: JSON.stringify(['application/pdf', 'image/jpeg', 'image/png']),
    versioningEnabled: false,
  },
  {
    code: 'QUITTANCE',
    label: 'Quittance de loyer',
    description: 'Quittance de loyer émise au locataire',
    scope: 'global',
    isSystem: true,
    isRequired: false,
    isActive: true,
    isSensitive: true,
    order: 30,
    icon: 'FileText',
    autoAssignThreshold: 0.90,
    validExtensions: JSON.stringify(['.pdf']),
    validMimeTypes: JSON.stringify(['application/pdf']),
    versioningEnabled: false,
  },

  // PROPERTY - Documents liés aux biens
  {
    code: 'ACTE_PROPRIETE',
    label: 'Acte de propriété',
    description: 'Acte notarié de propriété du bien',
    scope: 'property',
    isSystem: true,
    isRequired: true,
    isActive: true,
    isSensitive: true,
    order: 10,
    icon: 'FileCheck',
    regexFilename: '.*acte.*',
    validExtensions: JSON.stringify(['.pdf']),
    validMimeTypes: JSON.stringify(['application/pdf']),
    versioningEnabled: true,
  },
  {
    code: 'TITRE_PROPRIETE',
    label: 'Titre de propriété',
    description: 'Titre de propriété officiel',
    scope: 'property',
    isSystem: true,
    isRequired: true,
    isActive: true,
    isSensitive: true,
    order: 11,
    icon: 'Award',
    validExtensions: JSON.stringify(['.pdf']),
    validMimeTypes: JSON.stringify(['application/pdf']),
    versioningEnabled: true,
  },
  {
    code: 'DPE',
    label: 'Diagnostic de Performance Énergétique',
    description: 'DPE obligatoire pour la location',
    scope: 'property',
    isSystem: true,
    isRequired: true,
    isActive: true,
    isSensitive: false,
    order: 20,
    icon: 'Zap',
    autoAssignThreshold: 0.80,
    regexFilename: '.*dpe.*',
    validExtensions: JSON.stringify(['.pdf']),
    validMimeTypes: JSON.stringify(['application/pdf']),
    versioningEnabled: true,
    ocrProfileKey: 'dpe_diagnostics',
  },
  {
    code: 'DIAG_AMIANTE',
    label: 'Diagnostic amiante',
    description: 'Diagnostic amiante obligatoire',
    scope: 'property',
    isSystem: true,
    isRequired: true,
    isActive: true,
    isSensitive: false,
    order: 21,
    icon: 'AlertTriangle',
    validExtensions: JSON.stringify(['.pdf']),
    validMimeTypes: JSON.stringify(['application/pdf']),
    versioningEnabled: true,
  },
  {
    code: 'DIAG_PLOMB',
    label: 'Diagnostic plomb (CREP)',
    description: 'Constat de risque d\'exposition au plomb',
    scope: 'property',
    isSystem: true,
    isRequired: true,
    isActive: true,
    isSensitive: false,
    order: 22,
    icon: 'AlertTriangle',
    validExtensions: JSON.stringify(['.pdf']),
    validMimeTypes: JSON.stringify(['application/pdf']),
    versioningEnabled: true,
  },
  {
    code: 'DIAG_GAZ',
    label: 'Diagnostic gaz',
    description: 'Diagnostic installation gaz',
    scope: 'property',
    isSystem: true,
    isRequired: false,
    isActive: true,
    isSensitive: false,
    order: 23,
    icon: 'Flame',
    validExtensions: JSON.stringify(['.pdf']),
    validMimeTypes: JSON.stringify(['application/pdf']),
    versioningEnabled: true,
  },
  {
    code: 'DIAG_ELEC',
    label: 'Diagnostic électricité',
    description: 'Diagnostic installation électrique',
    scope: 'property',
    isSystem: true,
    isRequired: false,
    isActive: true,
    isSensitive: false,
    order: 24,
    icon: 'Zap',
    validExtensions: JSON.stringify(['.pdf']),
    validMimeTypes: JSON.stringify(['application/pdf']),
    versioningEnabled: true,
  },
  {
    code: 'TAXE_FONCIERE',
    label: 'Taxe foncière',
    description: 'Avis d\'imposition de taxe foncière',
    scope: 'property',
    isSystem: true,
    isRequired: false,
    isActive: true,
    isSensitive: true,
    order: 30,
    icon: 'FileText',
    regexFilename: '.*taxe.*fonciere.*',
    validExtensions: JSON.stringify(['.pdf']),
    validMimeTypes: JSON.stringify(['application/pdf']),
    versioningEnabled: false,
    ocrProfileKey: 'tax_notice',
  },
  {
    code: 'PLAN_BIEN',
    label: 'Plan du bien',
    description: 'Plans, schémas du bien immobilier',
    scope: 'property',
    isSystem: false,
    isRequired: false,
    isActive: true,
    isSensitive: false,
    order: 40,
    icon: 'Map',
    validExtensions: JSON.stringify(['.pdf', '.jpg', '.jpeg', '.png', '.dwg']),
    validMimeTypes: JSON.stringify(['application/pdf', 'image/jpeg', 'image/png']),
    versioningEnabled: true,
  },
  {
    code: 'PHOTO_BIEN',
    label: 'Photo du bien',
    description: 'Photos du bien immobilier',
    scope: 'property',
    isSystem: false,
    isRequired: false,
    isActive: true,
    isSensitive: false,
    order: 50,
    icon: 'Image',
    validExtensions: JSON.stringify(['.jpg', '.jpeg', '.png', '.heic']),
    validMimeTypes: JSON.stringify(['image/jpeg', 'image/png', 'image/heic']),
    versioningEnabled: false,
  },

  // LEASE - Documents liés aux baux
  {
    code: 'BAIL_SIGNE',
    label: 'Bail signé',
    description: 'Contrat de bail signé par les deux parties',
    scope: 'lease',
    isSystem: true,
    isRequired: true,
    isActive: true,
    isSensitive: true,
    order: 10,
    icon: 'FileSignature',
    autoAssignThreshold: 0.85,
    regexFilename: '.*bail.*sign.*',
    validExtensions: JSON.stringify(['.pdf']),
    validMimeTypes: JSON.stringify(['application/pdf']),
    versioningEnabled: true,
  },
  {
    code: 'EDL_ENTREE',
    label: 'État des lieux d\'entrée',
    description: 'État des lieux réalisé à l\'entrée du locataire',
    scope: 'lease',
    isSystem: true,
    isRequired: true,
    isActive: true,
    isSensitive: false,
    order: 20,
    icon: 'ClipboardCheck',
    regexFilename: '.*edl.*entree.*',
    validExtensions: JSON.stringify(['.pdf']),
    validMimeTypes: JSON.stringify(['application/pdf']),
    versioningEnabled: true,
  },
  {
    code: 'EDL_SORTIE',
    label: 'État des lieux de sortie',
    description: 'État des lieux réalisé à la sortie du locataire',
    scope: 'lease',
    isSystem: true,
    isRequired: false,
    isActive: true,
    isSensitive: false,
    order: 21,
    icon: 'ClipboardX',
    regexFilename: '.*edl.*sortie.*',
    validExtensions: JSON.stringify(['.pdf']),
    validMimeTypes: JSON.stringify(['application/pdf']),
    versioningEnabled: true,
  },
  {
    code: 'AVENANT_BAIL',
    label: 'Avenant au bail',
    description: 'Avenant modificatif du bail',
    scope: 'lease',
    isSystem: true,
    isRequired: false,
    isActive: true,
    isSensitive: true,
    order: 30,
    icon: 'FilePlus',
    regexFilename: '.*avenant.*',
    validExtensions: JSON.stringify(['.pdf']),
    validMimeTypes: JSON.stringify(['application/pdf']),
    versioningEnabled: true,
  },
  {
    code: 'ATTESTATION_ASSURANCE_LOCATAIRE',
    label: 'Attestation d\'assurance habitation',
    description: 'Attestation d\'assurance habitation du locataire',
    scope: 'lease',
    isSystem: true,
    isRequired: true,
    isActive: true,
    isSensitive: false,
    order: 40,
    icon: 'Shield',
    regexFilename: '.*attestation.*assurance.*',
    validExtensions: JSON.stringify(['.pdf', '.jpg', '.jpeg', '.png']),
    validMimeTypes: JSON.stringify(['application/pdf', 'image/jpeg', 'image/png']),
    versioningEnabled: true,
  },
  {
    code: 'PIECE_IDENTITE_LOCATAIRE',
    label: 'Pièce d\'identité du locataire',
    description: 'CNI, passeport ou titre de séjour du locataire',
    scope: 'lease',
    isSystem: true,
    isRequired: true,
    isActive: true,
    isSensitive: true,
    order: 50,
    icon: 'IdCard',
    validExtensions: JSON.stringify(['.pdf', '.jpg', '.jpeg', '.png']),
    validMimeTypes: JSON.stringify(['application/pdf', 'image/jpeg', 'image/png']),
    versioningEnabled: false,
  },
  {
    code: 'JUSTIFICATIF_REVENUS',
    label: 'Justificatif de revenus',
    description: 'Bulletins de salaire, avis d\'imposition',
    scope: 'lease',
    isSystem: true,
    isRequired: true,
    isActive: true,
    isSensitive: true,
    order: 60,
    icon: 'Banknote',
    validExtensions: JSON.stringify(['.pdf', '.jpg', '.jpeg', '.png']),
    validMimeTypes: JSON.stringify(['application/pdf', 'image/jpeg', 'image/png']),
    versioningEnabled: false,
  },
  {
    code: 'CONGE_LOCATAIRE',
    label: 'Préavis / Congé locataire',
    description: 'Lettre de préavis du locataire',
    scope: 'lease',
    isSystem: true,
    isRequired: false,
    isActive: true,
    isSensitive: false,
    order: 70,
    icon: 'LogOut',
    regexFilename: '.*conge.*|.*preavis.*',
    validExtensions: JSON.stringify(['.pdf', '.jpg', '.jpeg', '.png']),
    validMimeTypes: JSON.stringify(['application/pdf', 'image/jpeg', 'image/png']),
    versioningEnabled: true,
  },

  // TRANSACTION - Documents liés aux transactions
  {
    code: 'JUSTIFICATIF_PAIEMENT',
    label: 'Justificatif de paiement',
    description: 'Virement, chèque, reçu de paiement',
    scope: 'transaction',
    isSystem: true,
    isRequired: false,
    isActive: true,
    isSensitive: true,
    order: 10,
    icon: 'Receipt',
    validExtensions: JSON.stringify(['.pdf', '.jpg', '.jpeg', '.png']),
    validMimeTypes: JSON.stringify(['application/pdf', 'image/jpeg', 'image/png']),
    versioningEnabled: false,
  },
  {
    code: 'FACTURE_TRAVAUX',
    label: 'Facture de travaux',
    description: 'Facture de travaux ou réparations',
    scope: 'transaction',
    isSystem: false,
    isRequired: false,
    isActive: true,
    isSensitive: false,
    order: 20,
    icon: 'Wrench',
    regexFilename: '.*facture.*travaux.*',
    validExtensions: JSON.stringify(['.pdf', '.jpg', '.jpeg', '.png']),
    validMimeTypes: JSON.stringify(['application/pdf', 'image/jpeg', 'image/png']),
    versioningEnabled: false,
    ocrProfileKey: 'invoice',
  },
  {
    code: 'FACTURE_CHARGES',
    label: 'Facture de charges',
    description: 'Facture d\'eau, électricité, gaz, etc.',
    scope: 'transaction',
    isSystem: false,
    isRequired: false,
    isActive: true,
    isSensitive: false,
    order: 30,
    icon: 'Zap',
    regexFilename: '.*facture.*charge.*|.*electricite.*|.*eau.*|.*gaz.*',
    validExtensions: JSON.stringify(['.pdf', '.jpg', '.jpeg', '.png']),
    validMimeTypes: JSON.stringify(['application/pdf', 'image/jpeg', 'image/png']),
    versioningEnabled: false,
    ocrProfileKey: 'invoice',
  },
  {
    code: 'RECU_LOYER',
    label: 'Reçu de loyer',
    description: 'Reçu ou quittance de loyer',
    scope: 'transaction',
    isSystem: true,
    isRequired: false,
    isActive: true,
    isSensitive: true,
    order: 40,
    icon: 'FileText',
    regexFilename: '.*recu.*loyer.*|.*quittance.*',
    validExtensions: JSON.stringify(['.pdf']),
    validMimeTypes: JSON.stringify(['application/pdf']),
    versioningEnabled: false,
  },
  {
    code: 'RELEVE_BANCAIRE',
    label: 'Relevé bancaire',
    description: 'Relevé de compte bancaire',
    scope: 'transaction',
    isSystem: false,
    isRequired: false,
    isActive: true,
    isSensitive: true,
    order: 50,
    icon: 'Building',
    validExtensions: JSON.stringify(['.pdf', '.csv', '.ofx']),
    validMimeTypes: JSON.stringify(['application/pdf', 'text/csv']),
    versioningEnabled: false,
  },
];

export async function seedDocumentTypes() {
  console.log('🌱 Seeding document types...');

  for (const docType of documentTypesSeed) {
    await prisma.documentType.upsert({
      where: { code: docType.code },
      update: docType,
      create: docType,
    });
  }

  console.log(`✅ Seeded ${documentTypesSeed.length} document types`);
}

// Execute if run directly
seedDocumentTypes()
  .then(() => {
    console.log('✅ Document types seeded successfully');
    process.exit(0);
  })
  .catch((error) => {
    console.error('❌ Error seeding document types:', error);
    process.exit(1);
  })
  .finally(() => {
    prisma.$disconnect();
  });

