import type { PatrimoineSnapshotResult } from '@/features/patrimoine/hooks/usePatrimoineSnapshot';

/** Snapshot minimal pour tests UI / services (compléter avec overrides si besoin). */
export function minimalPatrimoineSnapshot(overrides: Partial<PatrimoineSnapshotResult> = {}): PatrimoineSnapshotResult {
  const base: PatrimoineSnapshotResult = {
    immobilierBrut: 200_000,
    dette: 80_000,
    immobilierNet: 120_000,
    revenuLocatifNet: 0,
    peaEtfValue: 10_000,
    cashDisponible: 5000,
    cashSecurite: 3000,
    patrimoineNetGlobal: 135_000,
    revenuGlobalEstime: 5000,
    marketRecommendation: null,
    dcaRecommended: 300,
    reinforceRecommended: 0,
    rendementEtfAnnuel: 0.07,
    reserveCashMoteur: 0,
    drawdownPercent: null,
    athDistancePercent: null,
    scoreAllocation: 55,
    allocationEtf: 10_000 / 135_000,
    allocationImmo: 120_000 / 135_000,
    cashExcess: 2000,
    investableCash: 2000,
    decisionFlags: {
      isMarketHigh: false,
      isMarketOpportunity: false,
      hasTooMuchCash: false,
      isImmoHeavy: false,
    },
    marketScore: null,
    marketScoreLabel: null,
    marketStatus: null,
    fiscalSimulationId: null,
    fiscalYear: null,
    hasFiscalSimulation: false,
    patrimoineReco: {
      primaryAction: 'WAIT',
      dcaAmount: 300,
      reinforceAmount: 0,
      message: 'Message reco.',
      level: 'INFO',
    },
    monthlyCapacity: 0,
    effortFiscalMensuel: null,
    netMonthlyFreeCash: 0,
    fiscalResteAPayer: null,
    fiscalMonthsRemaining: null,
    nextEvents: {
      nextTaxPayment: null,
      nextDcaDate: '2026-06-15T12:00:00.000Z',
      nextLoanPayment: null,
    },
    priorityActions: [],
    userObjective: 'equilibre',
    effectiveDcaDayOfMonth: 5,
    hasMarketData: false,
    projectionTrend: 'stagnation',
    projectionPatrimoineDeltaRatio: 0,
    selectedFiscalSimulationId: null,
    fiscalSimulationSelectionMode: 'AUTO',
    availableFiscalSimulations: [],
    fiscalSimulationWarning: null,
    selectedMarketInvestmentId: null,
    marketInvestmentSelectionMode: 'AUTO',
    availableMarketInvestments: [],
    marketSelectionWarning: null,
    sourceCash: 'PATRIMOINE',
    sourceDca: 'PATRIMOINE',
    sourceDcaDay: 'PATRIMOINE',
    marketProfileSummary: null,
    loading: false,
    error: null,
  };
  return { ...base, ...overrides };
}
